steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/himahi/agent-repo/agent-assistant:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/himahi/agent-repo/agent-assistant:latest'
    ]

images:
  - 'us-central1-docker.pkg.dev/himahi/agent-repo/agent-assistant:latest'